### ISSUE TITLE
Video Layout for 2015

### ISSUE THREAD

**Issue by Omarcito** [jsla/js.la#144]
![jsla_mortise_test png](https://cloud.githubusercontent.com/assets/1555240/6094724/6b4e9c46-aeec-11e4-9d69-7e50e5f77738.png)

Lets workshop what info we want displayed on the left hand side of the video.

I'm thinking I drop the Speaker Name and Talk Title, and rearrange the other stuff a bit to fill the gap.

Here is a Blank version if you wanna mess with it to show me what you want.
![jsla_mortise blank](https://cloud.githubusercontent.com/assets/1555240/6094750/829dd834-aeed-11e4-9050-0b386c520d4f.png)

also a link to the psd: https://drive.google.com/file/d/0B_buAmVsJcU8VzFFSVVyV3NUREE/view?usp=sharing

**Comment by emkay** [comment]
I dig this layout. We might want to tweak the line spacing and text align a little.

**Comment by jcblw** [comment]
![video](https://cloud.githubusercontent.com/assets/578259/6097657/25723f36-af7b-11e4-9132-d7a014ac144b.png)

I think we should have a very limited amount of information on this screen so that way to put focus on the content. Also I think the textured background is based off the old site. I think we should flatten to look more like the current site and to be a little more general for any new revisions to the site. I'm not in love at all with the color I chose in that mock.

Also I would say we should tighten up the branding. Here is a vector version of [our logo](https://github.com/jsla/js.la/blob/master/public/images/logo.svg), and the font being used is [Neutra Text](http://fontsup.com/font/neutra-text-tf-alt-bold.html).

Some references I used.

![screenshot from 2015-02-08 10 16 41](https://cloud.githubusercontent.com/assets/578259/6097684/ddafdac2-af7b-11e4-96c0-e491d79d0a86.png)
![screenshot from 2015-02-08 09 59 24](https://cloud.githubusercontent.com/assets/578259/6097685/ddb0c7ac-af7b-11e4-9f53-b3002e1d7baa.png)
![screenshot from 2015-02-08 09 58 42](https://cloud.githubusercontent.com/assets/578259/6097686/ddb1b252-af7b-11e4-8377-ec54d5209f86.png)

**Comment by Omarcito** [comment]
ill update the fonts to match everything. 

I'm not so much a fan of flat colors, it make it feel cheap to me. i tried a bunch with yellows and it was pretty terrible. like that nodeconf one makes my eyes hurt. 

ill play with toning down the texture this week and see how it looks

**Comment by jcblw** [comment]
Ok, we might want to looking doing something similar to the effect we do in the banner but with like a city scape, or palm trees.

**Comment by jcblw** [comment]
i know this is long past but just saw a video layout i though was dope.

<img width="863" alt="screen shot 2015-07-15 at 12 10 43 am" src="https://cloud.githubusercontent.com/assets/578259/8692765/222268ac-2a86-11e5-9674-53360408a30c.png">

super simple but clean.
